config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'
  
  resources :lists do
    resources :activities
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    belongs_to :list

end

app/models/list.rb
class List < ApplicationRecord
    has_one :destination
    has_many :activities, dependent: :destroy

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :set_list
    before_action :set_activity, only: [:show, :edit, :update, :destroy]

      def index
        @activities = @list.activites.all
      end
    
      def new
        @activity = @list.activities.new
      end
    
      def show
      end
    
      def edit
      end
    
      def create
        @activity = @list.activities.new(activity_params)
        if @activity.save
          redirect_to list_path(@list)
        else
          render :show # there is an issue with saving, this needs to be #new when you fix it
        end 
      end
    
      def update
        if @activity.update(activity_params)
          redirect_to list_path(@list)
        else
          render :edit
        end
      end
    
      def destroy
        @activity.destroy
        redirect_to list_path(@list)
      end
    
      private
    
      def activity_params 
        params.require(:activity).permit(:name, :image, :list_id)
      end

      def set_list
        @list = List.find(params[:list_id])
      end

      def set_activity
        @activity = Activity.find(params[:id])
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end 
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    List.find(params[:id]).destroy
    redirect_to lists_path
  end

  private

  def list_params 
    params.require(:list).permit(:name, :image)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/activities/_form.html.erb
<h1><%= @activity.id ? 'Edit Activity' : 'Add New Activity To List' %></h1>
<hr />

<%= form_for [@list, @activity] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
    <br />

    <%= f.submit 'Add Activity' %>
    
<% end %>

<hr />
<br/>
<%= link_to 'Go Back', list_path(@list) %>

app/views/activities/edit.html.erb
<%= render 'form' %>

app/views/activities/new.html.erb
<h1> ADD AN ITEM TO THE LIST </h1>

<% render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit List' : 'Create New List' %></h1>
<hr />
<%= form_for @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
    <br />

    <%= f.label :image %>
    <%= f.url_field :image %>
    <br />

    <%= f.submit %>
    
<% end %>

<hr />
<br />
<%= link_to 'Go Back', lists_path %>

app/views/lists/edit.html.erb
<%= render 'form' %>

app/views/lists/index.html.erb
<h1>Saved Bucket Lists</h1>

<%= link_to 'Create New Bucket List', new_list_path %>

<hr />

<ul>
<% @lists.each do |list| %>
    <li><h2><%= list.name %></h2>
    <%= link_to 'Show', list %>
    <%= link_to 'Edit', edit_list_path(list) %>
    <%= link_to 'Delete', list, method: :delete %>
    </li>
<% end %>
</ul>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
<h1>Bucket List Name: <%= @list.name %></h1>
<img src='<%= @list.image %>'/>

<hr />

<%= link_to 'Add an item', new_list_activity_path(@list) %>

<h2> List items: </h2>

<ol>
<% @list.activities.each do |activity| %>
    <li><h3><%= activity.name %> </h3>
    <%= link_to 'Edit', edit_list_activity_path(list_id: @list, id: activity) %>
    <%= link_to 'Delete', list_activity_path(list_id: @list, id: activity), method: :delete %>
    </li>
<% end %>
</ol>

<hr />
<br />
<%= link_to 'Go Back', lists_path %>